[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blogs = "229muqFhfrLZVP8q5CrSe7x1LyHLj54wopYdpX9Mzbuw"

[programs.devnet]
blogs = "229muqFhfrLZVP8q5CrSe7x1LyHLj54wopYdpX9Mzbuw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/phantom-keypair.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
